services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    restart: unless-stopped
    command: start-dev --import-realm
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "cat /proc/1/cmdline | grep -q keycloak || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm.json:/opt/keycloak/data/import/realm.json
    depends_on:
      mysql:
        condition: service_healthy      
  springboot:
    image: springcommunity/spring-framework-petclinic #placeholder image
    restart: unless-stopped
    env_file:
      - springboot.env
    ports:
      - "8081:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "cat /proc/1/cmdline | grep -q java || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  react:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - app-network 
    healthcheck:
      test: ["CMD-SHELL", "cat /proc/1/cmdline | grep -q nginx || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      springboot:
        condition: service_healthy
volumes:
  db_data:
  redis_data:
  keycloak_data:
networks:
  app-network:
    driver: bridge